// @/database/idioms.ts
import { Idiom } from '../types';

export const idioms: Idiom[] = [
    // --- EASY ---
    { term: 'Bite the bullet', definition: 'To endure a difficult or unpleasant situation with courage.', example: 'He had to bite the bullet and work late to finish the project.', difficulty: 'Easy' },
    { term: 'Break a leg', definition: 'A way to wish someone good luck, especially before a performance.', example: 'Before the play, I told my friend to break a leg.', difficulty: 'Easy' },
    { term: 'Hit the sack', definition: 'To go to bed.', example: 'I\'m exhausted, it\'s time for me to hit the sack.', difficulty: 'Easy' },
    { term: 'Piece of cake', definition: 'Something that is very easy to do.', example: 'The exam was a piece of cake.', difficulty: 'Easy' },
    { term: 'Call it a day', definition: 'To stop working on something.', example: 'We\'ve made enough progress for now, let\'s call it a day.', difficulty: 'Easy' },
    { term: 'Hang in there', definition: 'Don\'t give up.', example: 'I know you\'re tired, but hang in there, you\'re almost finished.', difficulty: 'Easy' },
    { term: 'Under the weather', definition: 'To feel ill.', example: 'I\'m feeling a bit under the weather today, so I\'m staying home.', difficulty: 'Easy' },
    { term: 'Pull someone\'s leg', definition: 'To joke with someone.', example: 'Relax, I\'m just pulling your leg. I didn\'t really break your laptop.', difficulty: 'Easy' },
    { term: 'Cost an arm and a leg', definition: 'To be very expensive.', example: 'That new car must have cost him an arm and a leg.', difficulty: 'Easy' },
    { term: 'See eye to eye', definition: 'To agree on something.', example: 'My sister and I don\'t see eye to eye on politics.', difficulty: 'Easy' },
    { term: 'When pigs fly', definition: 'Something that will never happen.', example: 'He\'ll clean his room when pigs fly.', difficulty: 'Easy' },
    { term: 'On cloud nine', definition: 'To be extremely happy and excited.', example: 'She\'s been on cloud nine ever since she got engaged.', difficulty: 'Easy' },
    { term: 'Get cold feet', definition: 'To become too frightened to do something you had planned to do.', example: 'He got cold feet and canceled the wedding.', difficulty: 'Easy' },
    { term: 'Rule of thumb', definition: 'A general or approximate rule based on experience or practice.', example: 'As a rule of thumb, you should double the recipe for a large party.', difficulty: 'Easy' },
    { term: 'A hot potato', definition: 'A controversial or sensitive issue that is difficult to handle.', example: 'The topic of tax increases became a political hot potato.', difficulty: 'Easy' },
    { term: 'Every cloud has a silver lining', definition: 'There is something good in every bad situation.', example: 'I was sad when I lost my job, but it gave me a chance to start my own business. Every cloud has a silver lining.', difficulty: 'Easy' },
    { term: 'It\'s raining cats and dogs', definition: 'It\'s raining very heavily.', example: 'I can\'t go for a walk now, it\'s raining cats and dogs outside.', difficulty: 'Easy' },
    { term: 'Fit as a fiddle', definition: 'To be in very good health.', example: 'My grandfather is 90 years old, but he is fit as a fiddle.', difficulty: 'Easy' },
    { term: 'A penny for your thoughts', definition: 'A way of asking what someone is thinking.', example: 'You\'ve been quiet for a while. A penny for your thoughts?', difficulty: 'Easy' },
    { term: 'Actions speak louder than words', definition: 'What you do is more important and shows your true intentions more than what you say.', example: 'He keeps promising to help, but actions speak louder than words.', difficulty: 'Easy' },
    { term: 'Jump to conclusions', definition: 'To make a decision about something too quickly, without knowing all the facts.', example: 'Don\'t jump to conclusions! You don\'t know the whole story.', difficulty: 'Easy' },
    { term: 'Get out of hand', definition: 'To become difficult to control.', example: 'The party started to get out of hand, so we called the police.', difficulty: 'Easy' },
    { term: 'Let someone off the hook', definition: 'To allow someone to escape from a difficult situation or from a responsibility.', example: 'I\'ll let you off the hook this time, but don\'t be late again.', difficulty: 'Easy' },
    { term: 'Better late than never', definition: 'It is better to do something late than not at all.', example: 'He finally paid me back the money he owed me. Well, better late than never.', difficulty: 'Easy' },
    // -- NEW EASY --
    { term: 'All ears', definition: 'Listening eagerly and carefully.', example: 'Tell me about your trip, I\'m all ears.', difficulty: 'Easy' },
    { term: 'Break the ice', definition: 'To do or say something to relieve tension or get conversation going.', example: 'He told a joke to break the ice at the start of the meeting.', difficulty: 'Easy' },
    { term: 'Butterflies in my stomach', definition: 'To feel very nervous.', example: 'I had butterflies in my stomach before my speech.', difficulty: 'Easy' },
    { term: 'Cold shoulder', definition: 'To deliberately ignore or be unfriendly to someone.', example: 'She gave me the cold shoulder after our argument.', difficulty: 'Easy' },
    { term: 'Couch potato', definition: 'A person who takes little or no exercise and watches a lot of television.', example: 'Don\'t be such a couch potato; go outside and play!', difficulty: 'Easy' },
    { term: 'Cry wolf', definition: 'To call for help when it is not needed.', example: 'If you cry wolf too many times, no one will believe you when you really need help.', difficulty: 'Easy' },
    { term: 'Down to earth', definition: 'Practical and realistic; humble.', example: 'Despite being a celebrity, she is very down to earth.', difficulty: 'Easy' },
    { term: 'Early bird', definition: 'A person who gets up or arrives early.', example: 'The early bird catches the worm.', difficulty: 'Easy' },
    { term: 'Eat like a bird', definition: 'To eat very little.', example: 'You eat like a bird; you haven\'t touched your dinner.', difficulty: 'Easy' },
    { term: 'Eat like a horse', definition: 'To eat a lot.', example: 'He eats like a horse but never gains weight.', difficulty: 'Easy' },
    { term: 'Fish out of water', definition: 'A person who feels uncomfortable in a new environment.', example: 'I felt like a fish out of water at the fancy dinner party.', difficulty: 'Easy' },
    { term: 'Get off my back', definition: 'Stop annoying or criticizing me.', example: 'I wish he would get off my back about cleaning my room.', difficulty: 'Easy' },
    { term: 'Go bananas', definition: 'To become extremely angry or excited.', example: 'The crowd went bananas when the band came on stage.', difficulty: 'Easy' },
    { term: 'Have a change of heart', definition: 'To change your opinion or how you feel about something.', example: 'He was going to sell his car, but he had a change of heart.', difficulty: 'Easy' },
    { term: 'Heart of gold', definition: 'To be very kind and generous.', example: 'She has a heart of gold and is always helping others.', difficulty: 'Easy' },
    { term: 'Hold your horses', definition: 'Wait a moment; be patient.', example: 'Hold your horses! We aren\'t ready to leave yet.', difficulty: 'Easy' },
    { term: 'In the same boat', definition: 'To be in the same difficult situation as someone else.', example: 'We both failed the test, so we are in the same boat.', difficulty: 'Easy' },
    { term: 'It rings a bell', definition: 'It sounds familiar.', example: 'Her name rings a bell, but I can\'t remember where I met her.', difficulty: 'Easy' },
    { term: 'Keep a secret', definition: 'To not tell anyone else information that is meant to be hidden.', example: 'Can you keep a secret? I\'m planning a surprise party.', difficulty: 'Easy' },
    { term: 'Night owl', definition: 'A person who is habitually active or wakeful at night.', example: 'I am a night owl, so I do my best work after midnight.', difficulty: 'Easy' },
    { term: 'Open book', definition: 'Someone who is easy to understand and does not hide their thoughts.', example: 'He is an open book; you always know what he is thinking.', difficulty: 'Easy' },
    { term: 'Sick as a dog', definition: 'Extremely ill.', example: 'I was sick as a dog after eating that bad seafood.', difficulty: 'Easy' },
    { term: 'Sleep on it', definition: 'To delay making a decision until the following day.', example: 'I can\'t decide right now; let me sleep on it.', difficulty: 'Easy' },
    { term: 'Sweet tooth', definition: 'A great liking for sweet-tasting foods.', example: 'I have a huge sweet tooth; I can\'t resist chocolate.', difficulty: 'Easy' },
    { term: 'Time flies', definition: 'Time passes very quickly.', example: 'Time flies when you are having fun.', difficulty: 'Easy' },


    // --- MEDIUM ---
    { term: 'Spill the beans', definition: 'To reveal a secret.', example: 'She spilled the beans about the surprise party.', difficulty: 'Medium' },
    { term: 'A blessing in disguise', definition: 'A good thing that seemed bad at first.', example: 'Losing that job was a blessing in disguise; I found a much better one.', difficulty: 'Medium' },
    { term: 'Go back to the drawing board', definition: 'To start over.', example: 'Our initial plan failed, so we have to go back to the drawing board.', difficulty: 'Medium' },
    { term: 'Let the cat out of the bag', definition: 'To accidentally reveal a secret.', example: 'He let the cat out of the bag about their wedding plans.', difficulty: 'Medium' },
    { term: 'On the ball', definition: 'Doing a good job; being alert and efficient.', example: 'Our new intern is really on the ball.', difficulty: 'Medium' },
    { term: 'Beat around the bush', definition: 'To avoid saying what you mean, usually because it is uncomfortable.', example: 'Stop beating around the bush and just tell me what happened.', difficulty: 'Medium' },
    { term: 'Kill two birds with one stone', definition: 'To achieve two things in a single action.', example: 'I can kill two birds with one stone by listening to an English podcast while I exercise.', difficulty: 'Medium' },
    { term: 'The ball is in your court', definition: 'It is up to you to make the next move or decision.', example: 'I\'ve given you my final offer; now the ball is in your court.', difficulty: 'Medium' },
    { term: 'Bite off more than you can chew', definition: 'To try to do something that is too difficult for you.', example: 'He bit off more than he could chew by taking on three projects at once.', difficulty: 'Medium' },
    { term: 'Add insult to injury', definition: 'To make a bad situation even worse.', example: 'My car broke down, and to add insult to injury, it started to rain.', difficulty: 'Medium' },
    { term: 'Barking up the wrong tree', definition: 'To pursue a mistaken course of action; to be wrong about something.', example: 'If you think I\'m responsible for the error, you\'re barking up the wrong tree.', difficulty: 'Medium' },
    { term: 'Face the music', definition: 'To accept criticism or punishment for something you have done.', example: 'After he was caught cheating, he had to face the music.', difficulty: 'Medium' },
    { term: 'A chip on your shoulder', definition: 'To seem angry all the time because you think you have been treated unfairly.', example: 'He has a chip on his shoulder about not getting the promotion.', difficulty: 'Medium' },
    { term: 'Go the extra mile', definition: 'To make a special effort to achieve something.', example: 'She always goes the extra mile for her customers.', difficulty: 'Medium' },
    { term: 'Cut to the chase', definition: 'To get to the point without wasting time.', example: 'I don\'t have much time, so let\'s cut to the chase.', difficulty: 'Medium' },
    { term: 'Down to the wire', definition: 'Something that ends at the last minute or last moment.', example: 'The game went down to the wire; it was a tie until the final second.', difficulty: 'Medium' },
    { term: 'Hear it on the grapevine', definition: 'To hear rumors about something or someone.', example: 'I heard on the grapevine that she\'s getting a promotion.', difficulty: 'Medium' },
    { term: 'Hit the nail on the head', definition: 'To describe exactly what is causing a situation or problem.', example: 'You really hit the nail on the head with that analysis.', difficulty: 'Medium' },
    { term: 'Sit on the fence', definition: 'To avoid making a decision or choice.', example: 'You can\'t sit on the fence any longer; you need to choose a side.', difficulty: 'Medium' },
    { term: 'Take with a grain of salt', definition: 'To not take what someone says too seriously.', example: 'He tends to exaggerate, so I take everything he says with a grain of salt.', difficulty: 'Medium' },
    { term: 'The whole nine yards', definition: 'Everything, all of it.', example: 'He wanted a new computer with a monitor, keyboard, mouse - the whole nine yards.', difficulty: 'Medium' },
    { term: 'Wouldn\'t be caught dead', definition: 'Would never like to do something because it\'s embarrassing.', example: 'I wouldn\'t be caught dead wearing an outfit like that.', difficulty: 'Medium' },
    { term: 'Your guess is as good as mine', definition: 'To have no idea what the answer is.', example: 'When will the train arrive? Your guess is as good as mine.', difficulty: 'Medium' },
    { term: 'A penny saved is a penny earned', definition: 'By saving money, you are increasing your wealth.', example: 'I\'m putting 10% of my paycheck into savings because a penny saved is a penny earned.', difficulty: 'Medium' },
    // -- NEW MEDIUM --
    { term: 'A breath of fresh air', definition: 'Someone or something that is new and refreshing.', example: 'After all the complaining, her positive attitude was a breath of fresh air.', difficulty: 'Medium' },
    { term: 'Add fuel to the fire', definition: 'To make a bad situation worse.', example: 'Don\'t argue with him now; it will only add fuel to the fire.', difficulty: 'Medium' },
    { term: 'As right as rain', definition: 'To feel perfectly healthy or well again.', example: 'After a good night\'s sleep, I felt as right as rain.', difficulty: 'Medium' },
    { term: 'Back to square one', definition: 'Having to start all over again.', example: 'The project failed, so we are back to square one.', difficulty: 'Medium' },
    { term: 'Bend over backwards', definition: 'To try very hard to do something to help someone.', example: 'She bent over backwards to make sure her guests were comfortable.', difficulty: 'Medium' },
    { term: 'Bite one\'s tongue', definition: 'To stop oneself from saying something.', example: 'I wanted to argue, but I bit my tongue to avoid a fight.', difficulty: 'Medium' },
    { term: 'Burn the candle at both ends', definition: 'To work or do other things from early in the morning until late at night.', example: 'You can\'t burn the candle at both ends forever; you need rest.', difficulty: 'Medium' },
    { term: 'Burn the midnight oil', definition: 'To stay up late working or studying.', example: 'I have a big exam tomorrow, so I\'ll be burning the midnight oil tonight.', difficulty: 'Medium' },
    { term: 'By the skin of your teeth', definition: 'By a very narrow margin; barely.', example: 'He passed the exam by the skin of his teeth.', difficulty: 'Medium' },
    { term: 'Call the shots', definition: 'To be the person in charge and make the decisions.', example: 'She calls the shots in this company.', difficulty: 'Medium' },
    { term: 'Caught red-handed', definition: 'Caught in the act of doing something wrong.', example: 'The thief was caught red-handed stealing the jewelry.', difficulty: 'Medium' },
    { term: 'Change one\'s tune', definition: 'To change one\'s opinion or manner.', example: 'He used to dislike the idea, but he changed his tune when he saw the profits.', difficulty: 'Medium' },
    { term: 'Chew the fat', definition: 'To chat in a friendly and leisurely way.', example: 'We sat on the porch and chewed the fat for hours.', difficulty: 'Medium' },
    { term: 'Clear the air', definition: 'To resolve a misunderstanding or bad feelings.', example: 'We need to talk to clear the air between us.', difficulty: 'Medium' },
    { term: 'Cost a pretty penny', definition: 'To be very expensive.', example: 'That diamond ring must have cost a pretty penny.', difficulty: 'Medium' },
    { term: 'Cut someone some slack', definition: 'To be less critical or severe with someone.', example: 'He\'s new here, so cut him some slack.', difficulty: 'Medium' },
    { term: 'Draw the line', definition: 'To set a limit on what one is willing to do or accept.', example: 'I don\'t mind helping, but I draw the line at doing his homework for him.', difficulty: 'Medium' },
    { term: 'Drive someone up the wall', definition: 'To annoy or irritate someone very much.', example: 'That loud music is driving me up the wall.', difficulty: 'Medium' },
    { term: 'Easier said than done', definition: 'Easy to say, but difficult to actually do.', example: 'Finding a cheap apartment in this city is easier said than done.', difficulty: 'Medium' },
    { term: 'Get something off your chest', definition: 'To tell someone about something that has been worrying you.', example: 'I need to get this off my chest: I was the one who broke the vase.', difficulty: 'Medium' },
    { term: 'Give someone the cold shoulder', definition: 'To ignore someone intentionally.', example: 'She gave him the cold shoulder at the party.', difficulty: 'Medium' },
    { term: 'Go with the flow', definition: 'To accept things as they happen.', example: 'I don\'t have a plan; I\'m just going to go with the flow.', difficulty: 'Medium' },
    { term: 'Hit the road', definition: 'To leave or start a journey.', example: 'It\'s getting late; we should hit the road.', difficulty: 'Medium' },
    { term: 'Keep your chin up', definition: 'To remain cheerful in a difficult situation.', example: 'Keep your chin up; things will get better soon.', difficulty: 'Medium' },
    { term: 'Make a long story short', definition: 'To summarize the main point of a story.', example: 'To make a long story short, we missed the flight and had to stay another night.', difficulty: 'Medium' },


    // --- HARD ---
    { term: 'The best of both worlds', definition: 'An ideal situation.', example: 'Working from home gives me the best of both worlds: a career and time with my family.', difficulty: 'Hard' },
    { term: 'Once in a blue moon', definition: 'Happens very rarely.', example: 'I only go to the opera once in a blue moon.', difficulty: 'Hard' },
    { term: 'The elephant in the room', definition: 'A major problem that is obviously present but avoided as a subject for discussion.', example: 'His gambling addiction was the elephant in the room at every family gathering.', difficulty: 'Hard' },
    { term: 'Cut corners', definition: 'To do something in the easiest, cheapest, or fastest way.', example: 'The company cut corners on safety regulations and now faces a lawsuit.', difficulty: 'Hard' },
    { term: 'Jump on the bandwagon', definition: 'To join a popular activity or trend.', example: 'After the team won the championship, thousands of new fans jumped on the bandwagon.', difficulty: 'Hard' },
    { term: 'Read between the lines', definition: 'To understand the hidden meaning in what is said or written.', example: 'She said she was fine, but reading between the lines, I could tell she was upset.', difficulty: 'Hard' },
    { term: 'Steal someone\'s thunder', definition: 'To take the credit for something someone else did.', example: 'My colleague stole my thunder when he presented my idea to the boss as his own.', difficulty: 'Hard' },
    { term: 'A leopard can\'t change its spots', definition: 'Used to say that someone\'s character will not change, even if they try.', example: 'I told him he should be more generous, but a leopard can\'t change its spots.', difficulty: 'Hard' },
    { term: 'Throw in the towel', definition: 'To give up or admit defeat.', example: 'After hours of trying to fix the code, the programmer finally threw in the towel.', difficulty: 'Hard' },
    { term: 'The writing is on the wall', definition: 'A sign that something bad is about to happen; a warning of failure.', example: 'When the company lost its biggest client, the writing was on the wall.', difficulty: 'Hard' },
    { term: 'To be long in the tooth', definition: 'To be old.', example: 'He\'s a bit long in the tooth to be starting a new career as a firefighter.', difficulty: 'Hard' },
    { term: 'A flash in the pan', definition: 'Something that is successful only for a short time and is not repeated.', example: 'His first album was a hit, but it turned out to be just a flash in the pan.', difficulty: 'Hard' },
    { term: 'Bury your head in the sand', definition: 'To ignore or avoid a problem, hoping it will go away.', example: 'You can\'t just bury your head in the sand; you have to deal with this issue.', difficulty: 'Hard' },
    { term: 'At the drop of a hat', definition: 'Without any hesitation; instantly.', example: 'If you need help, just call me. I can be there at the drop of a hat.', difficulty: 'Hard' },
    { term: 'Bite the dust', definition: 'To fail, die, or come to an end.', example: 'My old computer finally bit the dust.', difficulty: 'Hard' },
    { term: 'Don\'t count your chickens before they hatch', definition: 'Don\'t make plans for something that might not happen.', example: 'You might get the job, but don\'t count your chickens before they hatch.', difficulty: 'Hard' },
    { term: 'Elvis has left the building', definition: 'The show has come to an end; it\'s all over.', example: 'The concert was over, the lights came on, and we knew Elvis has left the building.', difficulty: 'Hard' },
    { term: 'Method to my madness', definition: 'A purpose in what one is doing, even though it seems crazy.', example: 'My desk is messy, but there is a method to my madness.', difficulty: 'Hard' },
    { term: 'Not playing with a full deck', definition: 'Someone who lacks intelligence or is mentally unstable.', example: 'He keeps talking to himself; I think he\'s not playing with a full deck.', difficulty: 'Hard' },
    { term: 'Saved by the bell', definition: 'Saved from a difficult situation at the last possible moment.', example: 'I was about to give the wrong answer, but then the teacher was interrupted. Saved by the bell!', difficulty: 'Hard' },
    { term: 'Take a rain check', definition: 'To politely decline an offer now, with the hope of accepting it later.', example: 'I can\'t go to dinner tonight, but can I take a rain check?', difficulty: 'Hard' },
    { term: 'The devil is in the details', definition: 'Small, seemingly insignificant things can cause the biggest problems.', example: 'The plan looks good, but the devil is in the details.', difficulty: 'Hard' },
    { term: 'Up in the air', definition: 'Plans are uncertain or unsure.', example: 'Our travel plans are still up in the air; we don\'t know where we\'re going yet.', difficulty: 'Hard' },
    // -- NEW HARD --
    { term: 'A bitter pill to swallow', definition: 'Something unpleasant that must be accepted.', example: 'Losing the championship was a bitter pill to swallow.', difficulty: 'Hard' },
    { term: 'A diamond in the rough', definition: 'Someone or something with potential that needs developing.', example: 'The house was a mess, but the architect saw it was a diamond in the rough.', difficulty: 'Hard' },
    { term: 'At the end of your rope', definition: 'Having no more patience or strength.', example: 'I am at the end of my rope with this broken computer.', difficulty: 'Hard' },
    { term: 'Beat a dead horse', definition: 'To waste effort on a matter that has already been resolved.', example: 'Discussing this topic further is just beating a dead horse.', difficulty: 'Hard' },
    { term: 'Between a rock and a hard place', definition: 'Facing a choice between two equally unpleasant alternatives.', example: 'I was stuck between a rock and a hard place: quit my job or take a pay cut.', difficulty: 'Hard' },
    { term: 'Burn your bridges', definition: 'To destroy relationships or opportunities so that you cannot return to them.', example: 'Be polite when you resign; don\'t burn your bridges.', difficulty: 'Hard' },
    { term: 'Curiosity killed the cat', definition: 'Being too curious can get you into trouble.', example: 'Stop asking so many questions; remember, curiosity killed the cat.', difficulty: 'Hard' },
    { term: 'Cut the mustard', definition: 'To meet the required standard.', example: 'He tried out for the team, but he just didn\'t cut the mustard.', difficulty: 'Hard' },
    { term: 'Devil\'s advocate', definition: 'Someone who argues against a dominant idea for the sake of debate.', example: 'I agree with you, but I\'ll play devil\'s advocate just to test your argument.', difficulty: 'Hard' },
    { term: 'Don\'t put all your eggs in one basket', definition: 'Do not risk everything on a single venture.', example: 'You should apply to several colleges; don\'t put all your eggs in one basket.', difficulty: 'Hard' },
    { term: 'Drastic times call for drastic measures', definition: 'When you are in a difficult situation, you may need to take extreme actions.', example: 'We have no money left, so we have to sell the house. Drastic times call for drastic measures.', difficulty: 'Hard' },
    { term: 'Get wind of something', definition: 'To hear a rumor or piece of information about something.', example: 'If the press gets wind of this scandal, we are in trouble.', difficulty: 'Hard' },
    { term: 'Go down in flames', definition: 'To fail spectacularly.', example: 'His presentation went down in flames because he wasn\'t prepared.', difficulty: 'Hard' },
    { term: 'Head over heels', definition: 'Deeply in love.', example: 'He fell head over heels for her the moment they met.', difficulty: 'Hard' },
    { term: 'Hit the hay', definition: 'To go to bed.', example: 'I\'m exhausted; I\'m going to hit the hay.', difficulty: 'Hard' },
    { term: 'It takes two to tango', definition: 'Both parties involved in a situation or argument are responsible for it.', example: 'Don\'t just blame him for the fight; it takes two to tango.', difficulty: 'Hard' },
    { term: 'Jump the gun', definition: 'To do something too soon.', example: 'They jumped the gun and announced the winner before counting all the votes.', difficulty: 'Hard' },
    { term: 'Keep something at bay', definition: 'To prevent something unpleasant from coming too near.', example: 'Vitamin C helps keep colds at bay.', difficulty: 'Hard' },
    { term: 'Kill them with kindness', definition: 'To cause a person discomfort by being excessively kind to them.', example: 'Instead of arguing with rude customers, I kill them with kindness.', difficulty: 'Hard' },
    { term: 'Leave well enough alone', definition: 'To refrain from changing something that is already satisfactory.', example: 'The system is working fine, so let\'s leave well enough alone.', difficulty: 'Hard' },
    { term: 'Make a mountain out of a molehill', definition: 'To exaggerate the importance of a small problem.', example: 'It\'s just a small scratch on the car; don\'t make a mountain out of a molehill.', difficulty: 'Hard' },
    { term: 'Play it by ear', definition: 'To decide how to deal with a situation as it develops.', example: 'I don\'t know how long the meeting will last, so let\'s just play it by ear.', difficulty: 'Hard' },
    { term: 'Put the wool over someone\'s eyes', definition: 'To deceive someone.', example: 'He tried to put the wool over my eyes, but I knew he was lying.', difficulty: 'Hard' },
    { term: 'Rain on someone\'s parade', definition: 'To spoil someone\'s plans or enthusiasm.', example: 'I hate to rain on your parade, but the concert has been canceled.', difficulty: 'Hard' },
    { term: 'Shoot the breeze', definition: 'To have a casual conversation.', example: 'We sat on the porch and shot the breeze for an hour.', difficulty: 'Hard' },
    { term: 'Skeleton in the closet', definition: 'A shocking or embarrassing secret from the past.', example: 'Every family has at least one skeleton in the closet.', difficulty: 'Hard' },


    // --- EXAM ---
    { term: 'A dime a dozen', definition: 'Very common and of no particular value.', example: 'Experts in that field are a dime a dozen.', difficulty: 'Exam' },
    { term: 'Cry over spilt milk', definition: 'To be unhappy about something that cannot be undone.', example: 'It\'s no use crying over spilt milk; the mistake is made and we have to move on.', difficulty: 'Exam' },
    { term: 'Get a taste of your own medicine', definition: 'To be treated in the same unpleasant way you have treated others.', example: 'The bully finally got a taste of his own medicine when the new student stood up to him.', difficulty: 'Exam' },
    { term: 'Let sleeping dogs lie', definition: 'To avoid restarting a conflict or argument.', example: 'I wanted to bring up our old argument, but I decided to let sleeping dogs lie.', difficulty: 'Exam' },
    { term: 'Miss the boat', definition: 'To miss an opportunity.', example: 'The tickets sold out in an hour, and I totally missed the boat.', difficulty: 'Exam' },
    { term: 'Through thick and thin', definition: 'Under all circumstances, no matter how difficult.', example: 'True friends stick together through thick and thin.', difficulty: 'Exam' },
    { term: 'Throw caution to the wind', definition: 'To take a risk.', example: 'She threw caution to the wind and quit her job to start her own business.', difficulty: 'Exam' },
    { term: 'Cross the Rubicon', definition: 'To make an irreversible decision or take a decisive step.', example: 'When he submitted his resignation, he knew he had crossed the Rubicon.', difficulty: 'Exam' },
    { term: 'A Pyrrhic victory', definition: 'A victory that comes at such a great cost that it is tantamount to defeat.', example: 'The company won the lawsuit, but it was a Pyrrhic victory that bankrupted them.', difficulty: 'Exam' },
    { term: 'Bury the hatchet', definition: 'To end a conflict and make peace.', example: 'After years of feuding, the two brothers finally decided to bury the hatchet.', difficulty: 'Exam' },
    { term: 'Keep one\'s cards close to one\'s chest', definition: 'To be secretive about one\'s plans or intentions.', example: 'The CEO kept his cards close to his chest regarding the upcoming merger.', difficulty: 'Exam' },
    { term: 'Run the gauntlet', definition: 'To endure a series of criticisms or attacks.', example: 'The new CEO had to run the gauntlet of angry shareholders at the meeting.', difficulty: 'Exam' },
    { term: 'Wild-goose chase', definition: 'A foolish and hopeless pursuit of something unattainable.', example: 'The detective realized he had been sent on a wild-goose chase.', difficulty: 'Exam' },
    { term: 'A wolf in sheep\'s clothing', definition: 'A person who pretends to be harmless or friendly but is actually hostile.', example: 'The unctuous salesperson was a wolf in sheep\'s clothing.', difficulty: 'Exam' },
    { term: 'A sea change', definition: 'A profound or notable transformation.', example: 'The internet has brought about a sea change in how we consume media.', difficulty: 'Exam' },
    { term: 'The sword of Damocles', definition: 'A constantly threatening danger.', example: 'With the final exams approaching, the sword of Damocles hung over the students.', difficulty: 'Exam' },
    { term: 'Fiddle while Rome burns', definition: 'To occupy oneself with unimportant matters and neglect priorities during a crisis.', example: 'The manager was organizing his desk while the company was going bankrupt; he was fiddling while Rome burns.', difficulty: 'Exam' },
    { term: 'Meet your Waterloo', definition: 'To encounter your final, decisive defeat.', example: 'The chess champion met his Waterloo in the final match against the young prodigy.', difficulty: 'Exam' },
    { term: 'A Trojan horse', definition: 'Something or someone that is intended to defeat or subvert from within.', example: 'The free software was a Trojan horse that installed malware on his computer.', difficulty: 'Exam' },
    { term: 'The Midas touch', definition: 'The ability to make money or be successful at everything one does.', example: 'Everything she invests in turns a profit; she truly has the Midas touch.', difficulty: 'Exam' },
    { term: 'An Achilles\' heel', definition: 'A weakness or vulnerable point.', example: 'His quick temper is his Achilles\' heel.', difficulty: 'Exam' },
    { term: 'Leave no stone unturned', definition: 'To try every possible course of action in order to achieve something.', example: 'The detectives left no stone unturned in their search for the missing child.', difficulty: 'Exam' },
    { term: 'Rest on your laurels', definition: 'To be so satisfied with what you have already done that you do not try to achieve anything new.', example: 'Even after winning the championship, the coach told the team not to rest on their laurels.', difficulty: 'Exam' },
    { term: 'Paint the town red', definition: 'To go out and enjoy oneself flamboyantly.', example: 'After their final exams, the students went out to paint the town red.', difficulty: 'Exam' },
    // -- NEW EXAM --
    { term: 'Albatross around one\'s neck', definition: 'A heavy burden of guilt or an obstacle that hinders success.', example: 'The failing business became an albatross around his neck.', difficulty: 'Exam' },
    { term: 'An axe to grind', definition: 'To have a private reason for doing or being involved in something.', example: 'He criticized the project not because it was bad, but because he had an axe to grind with the manager.', difficulty: 'Exam' },
    { term: 'Apple of discord', definition: 'Something that causes trouble or unhappiness.', example: 'The inheritance became an apple of discord among the siblings.', difficulty: 'Exam' },
    { term: 'Augean stables', definition: 'A condition or place marked by great accumulation of filth or corruption.', example: 'Cleaning up the corruption in the city government was like cleaning the Augean stables.', difficulty: 'Exam' },
    { term: 'Beyond the pale', definition: 'Outside the bounds of acceptable behavior.', example: 'His rude comments were simply beyond the pale.', difficulty: 'Exam' },
    { term: 'Bone of contention', definition: 'A subject or issue over which there is continuing disagreement.', example: 'The property line has been a bone of contention between the neighbors for years.', difficulty: 'Exam' },
    { term: 'Carry coals to Newcastle', definition: 'To do something pointless or superfluous.', example: 'Bringing more food to the potluck would be like carrying coals to Newcastle.', difficulty: 'Exam' },
    { term: 'Cast pearls before swine', definition: 'To offer something valuable to someone who does not understand or appreciate it.', example: 'Explaining Shakespeare to him is like casting pearls before swine.', difficulty: 'Exam' },
    { term: 'Dog in the manger', definition: 'Someone who keeps something that they do not want or use so that others cannot have it.', example: 'He refused to sell the vacant lot even though he wasn\'t using it, acting like a dog in the manger.', difficulty: 'Exam' },
    { term: 'Faustian bargain', definition: 'An agreement in which a person abandons his or her spiritual values or moral principles in order to obtain knowledge or power.', example: 'The politician struck a Faustian bargain to win the election.', difficulty: 'Exam' },
    { term: 'Fifth column', definition: 'A group within a country at war who are sympathetic to or working for its enemies.', example: 'The government feared a fifth column was undermining the war effort.', difficulty: 'Exam' },
    { term: 'Fly in the ointment', definition: 'A minor irritation that spoils the success or enjoyment of something.', example: 'The only fly in the ointment was the lack of parking at the venue.', difficulty: 'Exam' },
    { term: 'Gilded cage', definition: 'Living in luxury but without freedom.', example: 'Her life in the palace was nothing more than a gilded cage.', difficulty: 'Exam' },
    { term: 'Gordian knot', definition: 'An extremely difficult or involved problem.', example: 'The peace treaty was a Gordian knot that no diplomat could untie.', difficulty: 'Exam' },
    { term: 'Halcyon days', definition: 'A period of time in the past that was idylically happy and peaceful.', example: 'She often remembered the halcyon days of her youth.', difficulty: 'Exam' },
    { term: 'Hobson\'s choice', definition: 'A situation in which you have no choice because if you do not accept what is offered, you get nothing.', example: 'It was a Hobson\'s choice: take the pay cut or lose the job.', difficulty: 'Exam' },
    { term: 'Hoist with one\'s own petard', definition: 'To be caught in one\'s own trap.', example: 'The schemer was hoist with his own petard when his plan backfired.', difficulty: 'Exam' },
    { term: 'Ivory tower', definition: 'A state of privileged seclusion or separation from the facts and practicalities of the real world.', example: 'Academics are often accused of living in an ivory tower.', difficulty: 'Exam' },
    { term: 'Pandora\'s box', definition: 'A process that generates many complicated problems as the result of unwise interference in something.', example: 'Opening that file was like opening Pandora\'s box; it revealed months of errors.', difficulty: 'Exam' },
    { term: 'Parting shot', definition: 'A final remark, typically a cutting one, made by someone at the moment of departure.', example: 'Her parting shot was that she never liked his cooking anyway.', difficulty: 'Exam' },
    { term: 'Potemkin village', definition: 'An impressive facade or show designed to hide an undesirable fact or condition.', example: 'The prosperous downtown area was a Potemkin village hiding the city\'s poverty.', difficulty: 'Exam' },
    { term: 'Red herring', definition: 'Something, especially a clue, that is or is intended to be misleading or distracting.', example: 'The clues pointed to the butler, but that turned out to be a red herring.', difficulty: 'Exam' },
    { term: 'Scylla and Charybdis', definition: 'Being between two dangers and moving away from one means getting closer to the other.', example: 'The government was caught between Scylla and Charybdis regarding the budget.', difficulty: 'Exam' },
    { term: 'Sisyphean task', definition: 'A task that can never be completed.', example: 'Answering all these emails feels like a Sisyphean task.', difficulty: 'Exam' },
    { term: 'Swan song', definition: 'A person\'s final public performance or professional activity before retirement.', example: 'This match will be the tennis legend\'s swan song.', difficulty: 'Exam' },
    { term: 'The lion\'s share', definition: 'The major portion.', example: 'He did the lion\'s share of the work on the project.', difficulty: 'Exam' },
    { term: 'Throw the baby out with the bathwater', definition: 'To lose something good when you are trying to get rid of something bad.', example: 'We need to reform the system, but let\'s not throw the baby out with the bathwater.', difficulty: 'Exam' },
    { term: 'Tilting at windmills', definition: 'Attacking imaginary enemies.', example: 'Fighting against the inevitable change is like tilting at windmills.', difficulty: 'Exam' },
    { term: 'White elephant', definition: 'A possession that is useless or troublesome, especially one that is expensive to maintain.', example: 'The new stadium became a white elephant that the city couldn\'t afford to keep open.', difficulty: 'Exam' },
];